/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ProjectEnvironment } from "./ProjectEnvironment";
import { ProjectEnvironmentCountArgs } from "./ProjectEnvironmentCountArgs";
import { ProjectEnvironmentFindManyArgs } from "./ProjectEnvironmentFindManyArgs";
import { ProjectEnvironmentFindUniqueArgs } from "./ProjectEnvironmentFindUniqueArgs";
import { CreateProjectEnvironmentArgs } from "./CreateProjectEnvironmentArgs";
import { UpdateProjectEnvironmentArgs } from "./UpdateProjectEnvironmentArgs";
import { DeleteProjectEnvironmentArgs } from "./DeleteProjectEnvironmentArgs";
import { Project } from "../../project/base/Project";
import { ProjectEnvironmentService } from "../projectEnvironment.service";
@graphql.Resolver(() => ProjectEnvironment)
export class ProjectEnvironmentResolverBase {
  constructor(protected readonly service: ProjectEnvironmentService) {}

  async _projectEnvironmentsMeta(
    @graphql.Args() args: ProjectEnvironmentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ProjectEnvironment])
  async projectEnvironments(
    @graphql.Args() args: ProjectEnvironmentFindManyArgs
  ): Promise<ProjectEnvironment[]> {
    return this.service.projectEnvironments(args);
  }

  @graphql.Query(() => ProjectEnvironment, { nullable: true })
  async projectEnvironment(
    @graphql.Args() args: ProjectEnvironmentFindUniqueArgs
  ): Promise<ProjectEnvironment | null> {
    const result = await this.service.projectEnvironment(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ProjectEnvironment)
  async createProjectEnvironment(
    @graphql.Args() args: CreateProjectEnvironmentArgs
  ): Promise<ProjectEnvironment> {
    return await this.service.createProjectEnvironment({
      ...args,
      data: {
        ...args.data,

        project: {
          connect: args.data.project,
        },
      },
    });
  }

  @graphql.Mutation(() => ProjectEnvironment)
  async updateProjectEnvironment(
    @graphql.Args() args: UpdateProjectEnvironmentArgs
  ): Promise<ProjectEnvironment | null> {
    try {
      return await this.service.updateProjectEnvironment({
        ...args,
        data: {
          ...args.data,

          project: {
            connect: args.data.project,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ProjectEnvironment)
  async deleteProjectEnvironment(
    @graphql.Args() args: DeleteProjectEnvironmentArgs
  ): Promise<ProjectEnvironment | null> {
    try {
      return await this.service.deleteProjectEnvironment(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Project, {
    nullable: true,
    name: "project",
  })
  async getProject(
    @graphql.Parent() parent: ProjectEnvironment
  ): Promise<Project | null> {
    const result = await this.service.getProject(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
