/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  ProjectEnvironment as PrismaProjectEnvironment,
  Project as PrismaProject,
} from "@prisma/client";

export class ProjectEnvironmentServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ProjectEnvironmentCountArgs, "select">
  ): Promise<number> {
    return this.prisma.projectEnvironment.count(args);
  }

  async projectEnvironments(
    args: Prisma.ProjectEnvironmentFindManyArgs
  ): Promise<PrismaProjectEnvironment[]> {
    return this.prisma.projectEnvironment.findMany(args);
  }
  async projectEnvironment(
    args: Prisma.ProjectEnvironmentFindUniqueArgs
  ): Promise<PrismaProjectEnvironment | null> {
    return this.prisma.projectEnvironment.findUnique(args);
  }
  async createProjectEnvironment(
    args: Prisma.ProjectEnvironmentCreateArgs
  ): Promise<PrismaProjectEnvironment> {
    return this.prisma.projectEnvironment.create(args);
  }
  async updateProjectEnvironment(
    args: Prisma.ProjectEnvironmentUpdateArgs
  ): Promise<PrismaProjectEnvironment> {
    return this.prisma.projectEnvironment.update(args);
  }
  async deleteProjectEnvironment(
    args: Prisma.ProjectEnvironmentDeleteArgs
  ): Promise<PrismaProjectEnvironment> {
    return this.prisma.projectEnvironment.delete(args);
  }

  async getProject(parentId: string): Promise<PrismaProject | null> {
    return this.prisma.projectEnvironment
      .findUnique({
        where: { id: parentId },
      })
      .project();
  }
}
