/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProjectEnvironmentService } from "../projectEnvironment.service";
import { ProjectEnvironmentCreateInput } from "./ProjectEnvironmentCreateInput";
import { ProjectEnvironment } from "./ProjectEnvironment";
import { ProjectEnvironmentFindManyArgs } from "./ProjectEnvironmentFindManyArgs";
import { ProjectEnvironmentWhereUniqueInput } from "./ProjectEnvironmentWhereUniqueInput";
import { ProjectEnvironmentUpdateInput } from "./ProjectEnvironmentUpdateInput";

export class ProjectEnvironmentControllerBase {
  constructor(protected readonly service: ProjectEnvironmentService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ProjectEnvironment })
  async createProjectEnvironment(
    @common.Body() data: ProjectEnvironmentCreateInput
  ): Promise<ProjectEnvironment> {
    return await this.service.createProjectEnvironment({
      data: {
        ...data,

        project: {
          connect: data.project,
        },
      },
      select: {
        createdAt: true,
        deletedAt: true,
        id: true,
        metadata: true,
        name: true,

        project: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ProjectEnvironment] })
  @ApiNestedQuery(ProjectEnvironmentFindManyArgs)
  async projectEnvironments(
    @common.Req() request: Request
  ): Promise<ProjectEnvironment[]> {
    const args = plainToClass(ProjectEnvironmentFindManyArgs, request.query);
    return this.service.projectEnvironments({
      ...args,
      select: {
        createdAt: true,
        deletedAt: true,
        id: true,
        metadata: true,
        name: true,

        project: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ProjectEnvironment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async projectEnvironment(
    @common.Param() params: ProjectEnvironmentWhereUniqueInput
  ): Promise<ProjectEnvironment | null> {
    const result = await this.service.projectEnvironment({
      where: params,
      select: {
        createdAt: true,
        deletedAt: true,
        id: true,
        metadata: true,
        name: true,

        project: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ProjectEnvironment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateProjectEnvironment(
    @common.Param() params: ProjectEnvironmentWhereUniqueInput,
    @common.Body() data: ProjectEnvironmentUpdateInput
  ): Promise<ProjectEnvironment | null> {
    try {
      return await this.service.updateProjectEnvironment({
        where: params,
        data: {
          ...data,

          project: {
            connect: data.project,
          },
        },
        select: {
          createdAt: true,
          deletedAt: true,
          id: true,
          metadata: true,
          name: true,

          project: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ProjectEnvironment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteProjectEnvironment(
    @common.Param() params: ProjectEnvironmentWhereUniqueInput
  ): Promise<ProjectEnvironment | null> {
    try {
      return await this.service.deleteProjectEnvironment({
        where: params,
        select: {
          createdAt: true,
          deletedAt: true,
          id: true,
          metadata: true,
          name: true,

          project: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
