/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  IsOptional,
  ValidateNested,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { GitIntegrationCreateNestedManyWithoutAccountsInput } from "./GitIntegrationCreateNestedManyWithoutAccountsInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { ProjectCreateNestedManyWithoutAccountsInput } from "./ProjectCreateNestedManyWithoutAccountsInput";
import { TenantWhereUniqueInput } from "../../tenant/base/TenantWhereUniqueInput";

@InputType()
class AccountCreateInput {
  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  createdAt?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  deletedAt?: Date | null;

  @ApiProperty({
    required: false,
    type: () => GitIntegrationCreateNestedManyWithoutAccountsInput,
  })
  @ValidateNested()
  @Type(() => GitIntegrationCreateNestedManyWithoutAccountsInput)
  @IsOptional()
  @Field(() => GitIntegrationCreateNestedManyWithoutAccountsInput, {
    nullable: true,
  })
  gitIntegrations?: GitIntegrationCreateNestedManyWithoutAccountsInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  metadata?: InputJsonValue;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: () => ProjectCreateNestedManyWithoutAccountsInput,
  })
  @ValidateNested()
  @Type(() => ProjectCreateNestedManyWithoutAccountsInput)
  @IsOptional()
  @Field(() => ProjectCreateNestedManyWithoutAccountsInput, {
    nullable: true,
  })
  projects?: ProjectCreateNestedManyWithoutAccountsInput;

  @ApiProperty({
    required: true,
    type: () => TenantWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TenantWhereUniqueInput)
  @Field(() => TenantWhereUniqueInput)
  tenant!: TenantWhereUniqueInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  updatedAt?: Date | null;
}

export { AccountCreateInput as AccountCreateInput };
