/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ComponentRepositoryCreateNestedManyWithoutRepositoriesInput } from "./ComponentRepositoryCreateNestedManyWithoutRepositoriesInput";
import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { GitIntegrationWhereUniqueInput } from "../../gitIntegration/base/GitIntegrationWhereUniqueInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class RepositoryCreateInput {
  @ApiProperty({
    required: false,
    type: () => ComponentRepositoryCreateNestedManyWithoutRepositoriesInput,
  })
  @ValidateNested()
  @Type(() => ComponentRepositoryCreateNestedManyWithoutRepositoriesInput)
  @IsOptional()
  @Field(() => ComponentRepositoryCreateNestedManyWithoutRepositoriesInput, {
    nullable: true,
  })
  componentRepositories?: ComponentRepositoryCreateNestedManyWithoutRepositoriesInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  createdAt?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  deletedAt?: Date | null;

  @ApiProperty({
    required: true,
    type: () => GitIntegrationWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => GitIntegrationWhereUniqueInput)
  @Field(() => GitIntegrationWhereUniqueInput)
  gitIntegration!: GitIntegrationWhereUniqueInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  metadata?: InputJsonValue;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  updatedAt?: Date | null;
}

export { RepositoryCreateInput as RepositoryCreateInput };
