/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Component } from "./Component";
import { ComponentCountArgs } from "./ComponentCountArgs";
import { ComponentFindManyArgs } from "./ComponentFindManyArgs";
import { ComponentFindUniqueArgs } from "./ComponentFindUniqueArgs";
import { CreateComponentArgs } from "./CreateComponentArgs";
import { UpdateComponentArgs } from "./UpdateComponentArgs";
import { DeleteComponentArgs } from "./DeleteComponentArgs";
import { ComponentRepositoryFindManyArgs } from "../../componentRepository/base/ComponentRepositoryFindManyArgs";
import { ComponentRepository } from "../../componentRepository/base/ComponentRepository";
import { Project } from "../../project/base/Project";
import { ComponentService } from "../component.service";
@graphql.Resolver(() => Component)
export class ComponentResolverBase {
  constructor(protected readonly service: ComponentService) {}

  async _componentsMeta(
    @graphql.Args() args: ComponentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Component])
  async components(
    @graphql.Args() args: ComponentFindManyArgs
  ): Promise<Component[]> {
    return this.service.components(args);
  }

  @graphql.Query(() => Component, { nullable: true })
  async component(
    @graphql.Args() args: ComponentFindUniqueArgs
  ): Promise<Component | null> {
    const result = await this.service.component(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Component)
  async createComponent(
    @graphql.Args() args: CreateComponentArgs
  ): Promise<Component> {
    return await this.service.createComponent({
      ...args,
      data: {
        ...args.data,

        project: {
          connect: args.data.project,
        },
      },
    });
  }

  @graphql.Mutation(() => Component)
  async updateComponent(
    @graphql.Args() args: UpdateComponentArgs
  ): Promise<Component | null> {
    try {
      return await this.service.updateComponent({
        ...args,
        data: {
          ...args.data,

          project: {
            connect: args.data.project,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Component)
  async deleteComponent(
    @graphql.Args() args: DeleteComponentArgs
  ): Promise<Component | null> {
    try {
      return await this.service.deleteComponent(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [ComponentRepository], {
    name: "componentRepositories",
  })
  async findComponentRepositories(
    @graphql.Parent() parent: Component,
    @graphql.Args() args: ComponentRepositoryFindManyArgs
  ): Promise<ComponentRepository[]> {
    const results = await this.service.findComponentRepositories(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Project, {
    nullable: true,
    name: "project",
  })
  async getProject(
    @graphql.Parent() parent: Component
  ): Promise<Project | null> {
    const result = await this.service.getProject(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
