/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ComponentService } from "../component.service";
import { ComponentCreateInput } from "./ComponentCreateInput";
import { Component } from "./Component";
import { ComponentFindManyArgs } from "./ComponentFindManyArgs";
import { ComponentWhereUniqueInput } from "./ComponentWhereUniqueInput";
import { ComponentUpdateInput } from "./ComponentUpdateInput";
import { ComponentRepositoryFindManyArgs } from "../../componentRepository/base/ComponentRepositoryFindManyArgs";
import { ComponentRepository } from "../../componentRepository/base/ComponentRepository";
import { ComponentRepositoryWhereUniqueInput } from "../../componentRepository/base/ComponentRepositoryWhereUniqueInput";

export class ComponentControllerBase {
  constructor(protected readonly service: ComponentService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Component })
  async createComponent(
    @common.Body() data: ComponentCreateInput
  ): Promise<Component> {
    return await this.service.createComponent({
      data: {
        ...data,

        project: {
          connect: data.project,
        },
      },
      select: {
        createdAt: true,
        deletedAt: true,
        id: true,
        metadata: true,
        name: true,

        project: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Component] })
  @ApiNestedQuery(ComponentFindManyArgs)
  async components(@common.Req() request: Request): Promise<Component[]> {
    const args = plainToClass(ComponentFindManyArgs, request.query);
    return this.service.components({
      ...args,
      select: {
        createdAt: true,
        deletedAt: true,
        id: true,
        metadata: true,
        name: true,

        project: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Component })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async component(
    @common.Param() params: ComponentWhereUniqueInput
  ): Promise<Component | null> {
    const result = await this.service.component({
      where: params,
      select: {
        createdAt: true,
        deletedAt: true,
        id: true,
        metadata: true,
        name: true,

        project: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Component })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateComponent(
    @common.Param() params: ComponentWhereUniqueInput,
    @common.Body() data: ComponentUpdateInput
  ): Promise<Component | null> {
    try {
      return await this.service.updateComponent({
        where: params,
        data: {
          ...data,

          project: {
            connect: data.project,
          },
        },
        select: {
          createdAt: true,
          deletedAt: true,
          id: true,
          metadata: true,
          name: true,

          project: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Component })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteComponent(
    @common.Param() params: ComponentWhereUniqueInput
  ): Promise<Component | null> {
    try {
      return await this.service.deleteComponent({
        where: params,
        select: {
          createdAt: true,
          deletedAt: true,
          id: true,
          metadata: true,
          name: true,

          project: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/componentRepositories")
  @ApiNestedQuery(ComponentRepositoryFindManyArgs)
  async findComponentRepositories(
    @common.Req() request: Request,
    @common.Param() params: ComponentWhereUniqueInput
  ): Promise<ComponentRepository[]> {
    const query = plainToClass(ComponentRepositoryFindManyArgs, request.query);
    const results = await this.service.findComponentRepositories(params.id, {
      ...query,
      select: {
        component: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        deletedAt: true,
        id: true,
        metadata: true,

        repository: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/componentRepositories")
  async connectComponentRepositories(
    @common.Param() params: ComponentWhereUniqueInput,
    @common.Body() body: ComponentRepositoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      componentRepositories: {
        connect: body,
      },
    };
    await this.service.updateComponent({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/componentRepositories")
  async updateComponentRepositories(
    @common.Param() params: ComponentWhereUniqueInput,
    @common.Body() body: ComponentRepositoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      componentRepositories: {
        set: body,
      },
    };
    await this.service.updateComponent({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/componentRepositories")
  async disconnectComponentRepositories(
    @common.Param() params: ComponentWhereUniqueInput,
    @common.Body() body: ComponentRepositoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      componentRepositories: {
        disconnect: body,
      },
    };
    await this.service.updateComponent({
      where: params,
      data,
      select: { id: true },
    });
  }
}
