/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GithubAppService } from "../githubApp.service";
import { GithubAppCreateInput } from "./GithubAppCreateInput";
import { GithubApp } from "./GithubApp";
import { GithubAppFindManyArgs } from "./GithubAppFindManyArgs";
import { GithubAppWhereUniqueInput } from "./GithubAppWhereUniqueInput";
import { GithubAppUpdateInput } from "./GithubAppUpdateInput";

export class GithubAppControllerBase {
  constructor(protected readonly service: GithubAppService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: GithubApp })
  async createGithubApp(
    @common.Body() data: GithubAppCreateInput
  ): Promise<GithubApp> {
    return await this.service.createGithubApp({
      data: {
        ...data,

        gitIntegration: {
          connect: data.gitIntegration,
        },
      },
      select: {
        appId: true,
        createdAt: true,
        deletedAt: true,

        gitIntegration: {
          select: {
            id: true,
          },
        },

        id: true,
        installationId: true,
        metadata: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [GithubApp] })
  @ApiNestedQuery(GithubAppFindManyArgs)
  async githubApps(@common.Req() request: Request): Promise<GithubApp[]> {
    const args = plainToClass(GithubAppFindManyArgs, request.query);
    return this.service.githubApps({
      ...args,
      select: {
        appId: true,
        createdAt: true,
        deletedAt: true,

        gitIntegration: {
          select: {
            id: true,
          },
        },

        id: true,
        installationId: true,
        metadata: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: GithubApp })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async githubApp(
    @common.Param() params: GithubAppWhereUniqueInput
  ): Promise<GithubApp | null> {
    const result = await this.service.githubApp({
      where: params,
      select: {
        appId: true,
        createdAt: true,
        deletedAt: true,

        gitIntegration: {
          select: {
            id: true,
          },
        },

        id: true,
        installationId: true,
        metadata: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: GithubApp })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateGithubApp(
    @common.Param() params: GithubAppWhereUniqueInput,
    @common.Body() data: GithubAppUpdateInput
  ): Promise<GithubApp | null> {
    try {
      return await this.service.updateGithubApp({
        where: params,
        data: {
          ...data,

          gitIntegration: {
            connect: data.gitIntegration,
          },
        },
        select: {
          appId: true,
          createdAt: true,
          deletedAt: true,

          gitIntegration: {
            select: {
              id: true,
            },
          },

          id: true,
          installationId: true,
          metadata: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: GithubApp })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteGithubApp(
    @common.Param() params: GithubAppWhereUniqueInput
  ): Promise<GithubApp | null> {
    try {
      return await this.service.deleteGithubApp({
        where: params,
        select: {
          appId: true,
          createdAt: true,
          deletedAt: true,

          gitIntegration: {
            select: {
              id: true,
            },
          },

          id: true,
          installationId: true,
          metadata: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
