/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { GithubApp } from "./GithubApp";
import { GithubAppCountArgs } from "./GithubAppCountArgs";
import { GithubAppFindManyArgs } from "./GithubAppFindManyArgs";
import { GithubAppFindUniqueArgs } from "./GithubAppFindUniqueArgs";
import { CreateGithubAppArgs } from "./CreateGithubAppArgs";
import { UpdateGithubAppArgs } from "./UpdateGithubAppArgs";
import { DeleteGithubAppArgs } from "./DeleteGithubAppArgs";
import { GitIntegration } from "../../gitIntegration/base/GitIntegration";
import { GithubAppService } from "../githubApp.service";
@graphql.Resolver(() => GithubApp)
export class GithubAppResolverBase {
  constructor(protected readonly service: GithubAppService) {}

  async _githubAppsMeta(
    @graphql.Args() args: GithubAppCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [GithubApp])
  async githubApps(
    @graphql.Args() args: GithubAppFindManyArgs
  ): Promise<GithubApp[]> {
    return this.service.githubApps(args);
  }

  @graphql.Query(() => GithubApp, { nullable: true })
  async githubApp(
    @graphql.Args() args: GithubAppFindUniqueArgs
  ): Promise<GithubApp | null> {
    const result = await this.service.githubApp(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => GithubApp)
  async createGithubApp(
    @graphql.Args() args: CreateGithubAppArgs
  ): Promise<GithubApp> {
    return await this.service.createGithubApp({
      ...args,
      data: {
        ...args.data,

        gitIntegration: {
          connect: args.data.gitIntegration,
        },
      },
    });
  }

  @graphql.Mutation(() => GithubApp)
  async updateGithubApp(
    @graphql.Args() args: UpdateGithubAppArgs
  ): Promise<GithubApp | null> {
    try {
      return await this.service.updateGithubApp({
        ...args,
        data: {
          ...args.data,

          gitIntegration: {
            connect: args.data.gitIntegration,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => GithubApp)
  async deleteGithubApp(
    @graphql.Args() args: DeleteGithubAppArgs
  ): Promise<GithubApp | null> {
    try {
      return await this.service.deleteGithubApp(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => GitIntegration, {
    nullable: true,
    name: "gitIntegration",
  })
  async getGitIntegration(
    @graphql.Parent() parent: GithubApp
  ): Promise<GitIntegration | null> {
    const result = await this.service.getGitIntegration(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
