/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  GithubApp as PrismaGithubApp,
  GitIntegration as PrismaGitIntegration,
} from "@prisma/client";

export class GithubAppServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.GithubAppCountArgs, "select">
  ): Promise<number> {
    return this.prisma.githubApp.count(args);
  }

  async githubApps(
    args: Prisma.GithubAppFindManyArgs
  ): Promise<PrismaGithubApp[]> {
    return this.prisma.githubApp.findMany(args);
  }
  async githubApp(
    args: Prisma.GithubAppFindUniqueArgs
  ): Promise<PrismaGithubApp | null> {
    return this.prisma.githubApp.findUnique(args);
  }
  async createGithubApp(
    args: Prisma.GithubAppCreateArgs
  ): Promise<PrismaGithubApp> {
    return this.prisma.githubApp.create(args);
  }
  async updateGithubApp(
    args: Prisma.GithubAppUpdateArgs
  ): Promise<PrismaGithubApp> {
    return this.prisma.githubApp.update(args);
  }
  async deleteGithubApp(
    args: Prisma.GithubAppDeleteArgs
  ): Promise<PrismaGithubApp> {
    return this.prisma.githubApp.delete(args);
  }

  async getGitIntegration(
    parentId: string
  ): Promise<PrismaGitIntegration | null> {
    return this.prisma.githubApp
      .findUnique({
        where: { id: parentId },
      })
      .gitIntegration();
  }
}
