/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ComponentRepository } from "./ComponentRepository";
import { ComponentRepositoryCountArgs } from "./ComponentRepositoryCountArgs";
import { ComponentRepositoryFindManyArgs } from "./ComponentRepositoryFindManyArgs";
import { ComponentRepositoryFindUniqueArgs } from "./ComponentRepositoryFindUniqueArgs";
import { CreateComponentRepositoryArgs } from "./CreateComponentRepositoryArgs";
import { UpdateComponentRepositoryArgs } from "./UpdateComponentRepositoryArgs";
import { DeleteComponentRepositoryArgs } from "./DeleteComponentRepositoryArgs";
import { Component } from "../../component/base/Component";
import { Repository } from "../../repository/base/Repository";
import { ComponentRepositoryService } from "../componentRepository.service";
@graphql.Resolver(() => ComponentRepository)
export class ComponentRepositoryResolverBase {
  constructor(protected readonly service: ComponentRepositoryService) {}

  async _componentRepositoriesMeta(
    @graphql.Args() args: ComponentRepositoryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ComponentRepository])
  async componentRepositories(
    @graphql.Args() args: ComponentRepositoryFindManyArgs
  ): Promise<ComponentRepository[]> {
    return this.service.componentRepositories(args);
  }

  @graphql.Query(() => ComponentRepository, { nullable: true })
  async componentRepository(
    @graphql.Args() args: ComponentRepositoryFindUniqueArgs
  ): Promise<ComponentRepository | null> {
    const result = await this.service.componentRepository(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ComponentRepository)
  async createComponentRepository(
    @graphql.Args() args: CreateComponentRepositoryArgs
  ): Promise<ComponentRepository> {
    return await this.service.createComponentRepository({
      ...args,
      data: {
        ...args.data,

        component: {
          connect: args.data.component,
        },

        repository: {
          connect: args.data.repository,
        },
      },
    });
  }

  @graphql.Mutation(() => ComponentRepository)
  async updateComponentRepository(
    @graphql.Args() args: UpdateComponentRepositoryArgs
  ): Promise<ComponentRepository | null> {
    try {
      return await this.service.updateComponentRepository({
        ...args,
        data: {
          ...args.data,

          component: {
            connect: args.data.component,
          },

          repository: {
            connect: args.data.repository,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ComponentRepository)
  async deleteComponentRepository(
    @graphql.Args() args: DeleteComponentRepositoryArgs
  ): Promise<ComponentRepository | null> {
    try {
      return await this.service.deleteComponentRepository(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Component, {
    nullable: true,
    name: "component",
  })
  async getComponent(
    @graphql.Parent() parent: ComponentRepository
  ): Promise<Component | null> {
    const result = await this.service.getComponent(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Repository, {
    nullable: true,
    name: "repository",
  })
  async getRepository(
    @graphql.Parent() parent: ComponentRepository
  ): Promise<Repository | null> {
    const result = await this.service.getRepository(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
