/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ComponentRepositoryService } from "../componentRepository.service";
import { ComponentRepositoryCreateInput } from "./ComponentRepositoryCreateInput";
import { ComponentRepository } from "./ComponentRepository";
import { ComponentRepositoryFindManyArgs } from "./ComponentRepositoryFindManyArgs";
import { ComponentRepositoryWhereUniqueInput } from "./ComponentRepositoryWhereUniqueInput";
import { ComponentRepositoryUpdateInput } from "./ComponentRepositoryUpdateInput";

export class ComponentRepositoryControllerBase {
  constructor(protected readonly service: ComponentRepositoryService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ComponentRepository })
  async createComponentRepository(
    @common.Body() data: ComponentRepositoryCreateInput
  ): Promise<ComponentRepository> {
    return await this.service.createComponentRepository({
      data: {
        ...data,

        component: {
          connect: data.component,
        },

        repository: {
          connect: data.repository,
        },
      },
      select: {
        component: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        deletedAt: true,
        id: true,
        metadata: true,

        repository: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ComponentRepository] })
  @ApiNestedQuery(ComponentRepositoryFindManyArgs)
  async componentRepositories(
    @common.Req() request: Request
  ): Promise<ComponentRepository[]> {
    const args = plainToClass(ComponentRepositoryFindManyArgs, request.query);
    return this.service.componentRepositories({
      ...args,
      select: {
        component: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        deletedAt: true,
        id: true,
        metadata: true,

        repository: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ComponentRepository })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async componentRepository(
    @common.Param() params: ComponentRepositoryWhereUniqueInput
  ): Promise<ComponentRepository | null> {
    const result = await this.service.componentRepository({
      where: params,
      select: {
        component: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        deletedAt: true,
        id: true,
        metadata: true,

        repository: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ComponentRepository })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateComponentRepository(
    @common.Param() params: ComponentRepositoryWhereUniqueInput,
    @common.Body() data: ComponentRepositoryUpdateInput
  ): Promise<ComponentRepository | null> {
    try {
      return await this.service.updateComponentRepository({
        where: params,
        data: {
          ...data,

          component: {
            connect: data.component,
          },

          repository: {
            connect: data.repository,
          },
        },
        select: {
          component: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          deletedAt: true,
          id: true,
          metadata: true,

          repository: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ComponentRepository })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteComponentRepository(
    @common.Param() params: ComponentRepositoryWhereUniqueInput
  ): Promise<ComponentRepository | null> {
    try {
      return await this.service.deleteComponentRepository({
        where: params,
        select: {
          component: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          deletedAt: true,
          id: true,
          metadata: true,

          repository: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
