/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  ComponentRepository as PrismaComponentRepository,
  Component as PrismaComponent,
  Repository as PrismaRepository,
} from "@prisma/client";

export class ComponentRepositoryServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ComponentRepositoryCountArgs, "select">
  ): Promise<number> {
    return this.prisma.componentRepository.count(args);
  }

  async componentRepositories(
    args: Prisma.ComponentRepositoryFindManyArgs
  ): Promise<PrismaComponentRepository[]> {
    return this.prisma.componentRepository.findMany(args);
  }
  async componentRepository(
    args: Prisma.ComponentRepositoryFindUniqueArgs
  ): Promise<PrismaComponentRepository | null> {
    return this.prisma.componentRepository.findUnique(args);
  }
  async createComponentRepository(
    args: Prisma.ComponentRepositoryCreateArgs
  ): Promise<PrismaComponentRepository> {
    return this.prisma.componentRepository.create(args);
  }
  async updateComponentRepository(
    args: Prisma.ComponentRepositoryUpdateArgs
  ): Promise<PrismaComponentRepository> {
    return this.prisma.componentRepository.update(args);
  }
  async deleteComponentRepository(
    args: Prisma.ComponentRepositoryDeleteArgs
  ): Promise<PrismaComponentRepository> {
    return this.prisma.componentRepository.delete(args);
  }

  async getComponent(parentId: string): Promise<PrismaComponent | null> {
    return this.prisma.componentRepository
      .findUnique({
        where: { id: parentId },
      })
      .component();
  }

  async getRepository(parentId: string): Promise<PrismaRepository | null> {
    return this.prisma.componentRepository
      .findUnique({
        where: { id: parentId },
      })
      .repository();
  }
}
