/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AccountWhereUniqueInput } from "../../account/base/AccountWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { GithubAppUpdateManyWithoutGitIntegrationsInput } from "./GithubAppUpdateManyWithoutGitIntegrationsInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { RepositoryUpdateManyWithoutGitIntegrationsInput } from "./RepositoryUpdateManyWithoutGitIntegrationsInput";

@InputType()
class GitIntegrationUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AccountWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AccountWhereUniqueInput)
  @IsOptional()
  @Field(() => AccountWhereUniqueInput, {
    nullable: true,
  })
  account?: AccountWhereUniqueInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  createdAt?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  deletedAt?: Date | null;

  @ApiProperty({
    required: false,
    type: () => GithubAppUpdateManyWithoutGitIntegrationsInput,
  })
  @ValidateNested()
  @Type(() => GithubAppUpdateManyWithoutGitIntegrationsInput)
  @IsOptional()
  @Field(() => GithubAppUpdateManyWithoutGitIntegrationsInput, {
    nullable: true,
  })
  githubApps?: GithubAppUpdateManyWithoutGitIntegrationsInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  metadata?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => RepositoryUpdateManyWithoutGitIntegrationsInput,
  })
  @ValidateNested()
  @Type(() => RepositoryUpdateManyWithoutGitIntegrationsInput)
  @IsOptional()
  @Field(() => RepositoryUpdateManyWithoutGitIntegrationsInput, {
    nullable: true,
  })
  repositories?: RepositoryUpdateManyWithoutGitIntegrationsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  updatedAt?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  url?: string;
}

export { GitIntegrationUpdateInput as GitIntegrationUpdateInput };
