/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GitIntegrationService } from "../gitIntegration.service";
import { GitIntegrationCreateInput } from "./GitIntegrationCreateInput";
import { GitIntegration } from "./GitIntegration";
import { GitIntegrationFindManyArgs } from "./GitIntegrationFindManyArgs";
import { GitIntegrationWhereUniqueInput } from "./GitIntegrationWhereUniqueInput";
import { GitIntegrationUpdateInput } from "./GitIntegrationUpdateInput";
import { GithubAppFindManyArgs } from "../../githubApp/base/GithubAppFindManyArgs";
import { GithubApp } from "../../githubApp/base/GithubApp";
import { GithubAppWhereUniqueInput } from "../../githubApp/base/GithubAppWhereUniqueInput";
import { RepositoryFindManyArgs } from "../../repository/base/RepositoryFindManyArgs";
import { Repository } from "../../repository/base/Repository";
import { RepositoryWhereUniqueInput } from "../../repository/base/RepositoryWhereUniqueInput";

export class GitIntegrationControllerBase {
  constructor(protected readonly service: GitIntegrationService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: GitIntegration })
  async createGitIntegration(
    @common.Body() data: GitIntegrationCreateInput
  ): Promise<GitIntegration> {
    return await this.service.createGitIntegration({
      data: {
        ...data,

        account: {
          connect: data.account,
        },
      },
      select: {
        account: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        deletedAt: true,
        id: true,
        metadata: true,
        updatedAt: true,
        url: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [GitIntegration] })
  @ApiNestedQuery(GitIntegrationFindManyArgs)
  async gitIntegrations(
    @common.Req() request: Request
  ): Promise<GitIntegration[]> {
    const args = plainToClass(GitIntegrationFindManyArgs, request.query);
    return this.service.gitIntegrations({
      ...args,
      select: {
        account: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        deletedAt: true,
        id: true,
        metadata: true,
        updatedAt: true,
        url: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: GitIntegration })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async gitIntegration(
    @common.Param() params: GitIntegrationWhereUniqueInput
  ): Promise<GitIntegration | null> {
    const result = await this.service.gitIntegration({
      where: params,
      select: {
        account: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        deletedAt: true,
        id: true,
        metadata: true,
        updatedAt: true,
        url: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: GitIntegration })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateGitIntegration(
    @common.Param() params: GitIntegrationWhereUniqueInput,
    @common.Body() data: GitIntegrationUpdateInput
  ): Promise<GitIntegration | null> {
    try {
      return await this.service.updateGitIntegration({
        where: params,
        data: {
          ...data,

          account: {
            connect: data.account,
          },
        },
        select: {
          account: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          deletedAt: true,
          id: true,
          metadata: true,
          updatedAt: true,
          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: GitIntegration })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteGitIntegration(
    @common.Param() params: GitIntegrationWhereUniqueInput
  ): Promise<GitIntegration | null> {
    try {
      return await this.service.deleteGitIntegration({
        where: params,
        select: {
          account: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          deletedAt: true,
          id: true,
          metadata: true,
          updatedAt: true,
          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/githubApps")
  @ApiNestedQuery(GithubAppFindManyArgs)
  async findGithubApps(
    @common.Req() request: Request,
    @common.Param() params: GitIntegrationWhereUniqueInput
  ): Promise<GithubApp[]> {
    const query = plainToClass(GithubAppFindManyArgs, request.query);
    const results = await this.service.findGithubApps(params.id, {
      ...query,
      select: {
        appId: true,
        createdAt: true,
        deletedAt: true,

        gitIntegration: {
          select: {
            id: true,
          },
        },

        id: true,
        installationId: true,
        metadata: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/githubApps")
  async connectGithubApps(
    @common.Param() params: GitIntegrationWhereUniqueInput,
    @common.Body() body: GithubAppWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      githubApps: {
        connect: body,
      },
    };
    await this.service.updateGitIntegration({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/githubApps")
  async updateGithubApps(
    @common.Param() params: GitIntegrationWhereUniqueInput,
    @common.Body() body: GithubAppWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      githubApps: {
        set: body,
      },
    };
    await this.service.updateGitIntegration({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/githubApps")
  async disconnectGithubApps(
    @common.Param() params: GitIntegrationWhereUniqueInput,
    @common.Body() body: GithubAppWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      githubApps: {
        disconnect: body,
      },
    };
    await this.service.updateGitIntegration({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/repositories")
  @ApiNestedQuery(RepositoryFindManyArgs)
  async findRepositories(
    @common.Req() request: Request,
    @common.Param() params: GitIntegrationWhereUniqueInput
  ): Promise<Repository[]> {
    const query = plainToClass(RepositoryFindManyArgs, request.query);
    const results = await this.service.findRepositories(params.id, {
      ...query,
      select: {
        createdAt: true,
        deletedAt: true,

        gitIntegration: {
          select: {
            id: true,
          },
        },

        id: true,
        metadata: true,
        name: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/repositories")
  async connectRepositories(
    @common.Param() params: GitIntegrationWhereUniqueInput,
    @common.Body() body: RepositoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      repositories: {
        connect: body,
      },
    };
    await this.service.updateGitIntegration({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/repositories")
  async updateRepositories(
    @common.Param() params: GitIntegrationWhereUniqueInput,
    @common.Body() body: RepositoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      repositories: {
        set: body,
      },
    };
    await this.service.updateGitIntegration({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/repositories")
  async disconnectRepositories(
    @common.Param() params: GitIntegrationWhereUniqueInput,
    @common.Body() body: RepositoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      repositories: {
        disconnect: body,
      },
    };
    await this.service.updateGitIntegration({
      where: params,
      data,
      select: { id: true },
    });
  }
}
