/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  GitIntegration as PrismaGitIntegration,
  GithubApp as PrismaGithubApp,
  Repository as PrismaRepository,
  Account as PrismaAccount,
} from "@prisma/client";

export class GitIntegrationServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.GitIntegrationCountArgs, "select">
  ): Promise<number> {
    return this.prisma.gitIntegration.count(args);
  }

  async gitIntegrations(
    args: Prisma.GitIntegrationFindManyArgs
  ): Promise<PrismaGitIntegration[]> {
    return this.prisma.gitIntegration.findMany(args);
  }
  async gitIntegration(
    args: Prisma.GitIntegrationFindUniqueArgs
  ): Promise<PrismaGitIntegration | null> {
    return this.prisma.gitIntegration.findUnique(args);
  }
  async createGitIntegration(
    args: Prisma.GitIntegrationCreateArgs
  ): Promise<PrismaGitIntegration> {
    return this.prisma.gitIntegration.create(args);
  }
  async updateGitIntegration(
    args: Prisma.GitIntegrationUpdateArgs
  ): Promise<PrismaGitIntegration> {
    return this.prisma.gitIntegration.update(args);
  }
  async deleteGitIntegration(
    args: Prisma.GitIntegrationDeleteArgs
  ): Promise<PrismaGitIntegration> {
    return this.prisma.gitIntegration.delete(args);
  }

  async findGithubApps(
    parentId: string,
    args: Prisma.GithubAppFindManyArgs
  ): Promise<PrismaGithubApp[]> {
    return this.prisma.gitIntegration
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .githubApps(args);
  }

  async findRepositories(
    parentId: string,
    args: Prisma.RepositoryFindManyArgs
  ): Promise<PrismaRepository[]> {
    return this.prisma.gitIntegration
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .repositories(args);
  }

  async getAccount(parentId: string): Promise<PrismaAccount | null> {
    return this.prisma.gitIntegration
      .findUnique({
        where: { id: parentId },
      })
      .account();
  }
}
