/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { GitIntegration } from "./GitIntegration";
import { GitIntegrationCountArgs } from "./GitIntegrationCountArgs";
import { GitIntegrationFindManyArgs } from "./GitIntegrationFindManyArgs";
import { GitIntegrationFindUniqueArgs } from "./GitIntegrationFindUniqueArgs";
import { CreateGitIntegrationArgs } from "./CreateGitIntegrationArgs";
import { UpdateGitIntegrationArgs } from "./UpdateGitIntegrationArgs";
import { DeleteGitIntegrationArgs } from "./DeleteGitIntegrationArgs";
import { GithubAppFindManyArgs } from "../../githubApp/base/GithubAppFindManyArgs";
import { GithubApp } from "../../githubApp/base/GithubApp";
import { RepositoryFindManyArgs } from "../../repository/base/RepositoryFindManyArgs";
import { Repository } from "../../repository/base/Repository";
import { Account } from "../../account/base/Account";
import { GitIntegrationService } from "../gitIntegration.service";
@graphql.Resolver(() => GitIntegration)
export class GitIntegrationResolverBase {
  constructor(protected readonly service: GitIntegrationService) {}

  async _gitIntegrationsMeta(
    @graphql.Args() args: GitIntegrationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [GitIntegration])
  async gitIntegrations(
    @graphql.Args() args: GitIntegrationFindManyArgs
  ): Promise<GitIntegration[]> {
    return this.service.gitIntegrations(args);
  }

  @graphql.Query(() => GitIntegration, { nullable: true })
  async gitIntegration(
    @graphql.Args() args: GitIntegrationFindUniqueArgs
  ): Promise<GitIntegration | null> {
    const result = await this.service.gitIntegration(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => GitIntegration)
  async createGitIntegration(
    @graphql.Args() args: CreateGitIntegrationArgs
  ): Promise<GitIntegration> {
    return await this.service.createGitIntegration({
      ...args,
      data: {
        ...args.data,

        account: {
          connect: args.data.account,
        },
      },
    });
  }

  @graphql.Mutation(() => GitIntegration)
  async updateGitIntegration(
    @graphql.Args() args: UpdateGitIntegrationArgs
  ): Promise<GitIntegration | null> {
    try {
      return await this.service.updateGitIntegration({
        ...args,
        data: {
          ...args.data,

          account: {
            connect: args.data.account,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => GitIntegration)
  async deleteGitIntegration(
    @graphql.Args() args: DeleteGitIntegrationArgs
  ): Promise<GitIntegration | null> {
    try {
      return await this.service.deleteGitIntegration(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [GithubApp], { name: "githubApps" })
  async findGithubApps(
    @graphql.Parent() parent: GitIntegration,
    @graphql.Args() args: GithubAppFindManyArgs
  ): Promise<GithubApp[]> {
    const results = await this.service.findGithubApps(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Repository], { name: "repositories" })
  async findRepositories(
    @graphql.Parent() parent: GitIntegration,
    @graphql.Args() args: RepositoryFindManyArgs
  ): Promise<Repository[]> {
    const results = await this.service.findRepositories(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Account, {
    nullable: true,
    name: "account",
  })
  async getAccount(
    @graphql.Parent() parent: GitIntegration
  ): Promise<Account | null> {
    const result = await this.service.getAccount(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
