/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AccountWhereUniqueInput } from "../../account/base/AccountWhereUniqueInput";
import {
  ValidateNested,
  IsDate,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { GithubAppCreateNestedManyWithoutGitIntegrationsInput } from "./GithubAppCreateNestedManyWithoutGitIntegrationsInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { RepositoryCreateNestedManyWithoutGitIntegrationsInput } from "./RepositoryCreateNestedManyWithoutGitIntegrationsInput";

@InputType()
class GitIntegrationCreateInput {
  @ApiProperty({
    required: true,
    type: () => AccountWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AccountWhereUniqueInput)
  @Field(() => AccountWhereUniqueInput)
  account!: AccountWhereUniqueInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  createdAt?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  deletedAt?: Date | null;

  @ApiProperty({
    required: false,
    type: () => GithubAppCreateNestedManyWithoutGitIntegrationsInput,
  })
  @ValidateNested()
  @Type(() => GithubAppCreateNestedManyWithoutGitIntegrationsInput)
  @IsOptional()
  @Field(() => GithubAppCreateNestedManyWithoutGitIntegrationsInput, {
    nullable: true,
  })
  githubApps?: GithubAppCreateNestedManyWithoutGitIntegrationsInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  metadata?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => RepositoryCreateNestedManyWithoutGitIntegrationsInput,
  })
  @ValidateNested()
  @Type(() => RepositoryCreateNestedManyWithoutGitIntegrationsInput)
  @IsOptional()
  @Field(() => RepositoryCreateNestedManyWithoutGitIntegrationsInput, {
    nullable: true,
  })
  repositories?: RepositoryCreateNestedManyWithoutGitIntegrationsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  updatedAt?: Date | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  url!: string;
}

export { GitIntegrationCreateInput as GitIntegrationCreateInput };
