/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProjectService } from "../project.service";
import { ProjectCreateInput } from "./ProjectCreateInput";
import { Project } from "./Project";
import { ProjectFindManyArgs } from "./ProjectFindManyArgs";
import { ProjectWhereUniqueInput } from "./ProjectWhereUniqueInput";
import { ProjectUpdateInput } from "./ProjectUpdateInput";
import { ComponentFindManyArgs } from "../../component/base/ComponentFindManyArgs";
import { Component } from "../../component/base/Component";
import { ComponentWhereUniqueInput } from "../../component/base/ComponentWhereUniqueInput";
import { ProjectEnvironmentFindManyArgs } from "../../projectEnvironment/base/ProjectEnvironmentFindManyArgs";
import { ProjectEnvironment } from "../../projectEnvironment/base/ProjectEnvironment";
import { ProjectEnvironmentWhereUniqueInput } from "../../projectEnvironment/base/ProjectEnvironmentWhereUniqueInput";

export class ProjectControllerBase {
  constructor(protected readonly service: ProjectService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Project })
  async createProject(
    @common.Body() data: ProjectCreateInput
  ): Promise<Project> {
    return await this.service.createProject({
      data: {
        ...data,

        account: {
          connect: data.account,
        },
      },
      select: {
        account: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        deletedAt: true,
        id: true,
        metadata: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Project] })
  @ApiNestedQuery(ProjectFindManyArgs)
  async projects(@common.Req() request: Request): Promise<Project[]> {
    const args = plainToClass(ProjectFindManyArgs, request.query);
    return this.service.projects({
      ...args,
      select: {
        account: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        deletedAt: true,
        id: true,
        metadata: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Project })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async project(
    @common.Param() params: ProjectWhereUniqueInput
  ): Promise<Project | null> {
    const result = await this.service.project({
      where: params,
      select: {
        account: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        deletedAt: true,
        id: true,
        metadata: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Project })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateProject(
    @common.Param() params: ProjectWhereUniqueInput,
    @common.Body() data: ProjectUpdateInput
  ): Promise<Project | null> {
    try {
      return await this.service.updateProject({
        where: params,
        data: {
          ...data,

          account: {
            connect: data.account,
          },
        },
        select: {
          account: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          deletedAt: true,
          id: true,
          metadata: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Project })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteProject(
    @common.Param() params: ProjectWhereUniqueInput
  ): Promise<Project | null> {
    try {
      return await this.service.deleteProject({
        where: params,
        select: {
          account: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          deletedAt: true,
          id: true,
          metadata: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/components")
  @ApiNestedQuery(ComponentFindManyArgs)
  async findComponents(
    @common.Req() request: Request,
    @common.Param() params: ProjectWhereUniqueInput
  ): Promise<Component[]> {
    const query = plainToClass(ComponentFindManyArgs, request.query);
    const results = await this.service.findComponents(params.id, {
      ...query,
      select: {
        createdAt: true,
        deletedAt: true,
        id: true,
        metadata: true,
        name: true,

        project: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/components")
  async connectComponents(
    @common.Param() params: ProjectWhereUniqueInput,
    @common.Body() body: ComponentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      components: {
        connect: body,
      },
    };
    await this.service.updateProject({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/components")
  async updateComponents(
    @common.Param() params: ProjectWhereUniqueInput,
    @common.Body() body: ComponentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      components: {
        set: body,
      },
    };
    await this.service.updateProject({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/components")
  async disconnectComponents(
    @common.Param() params: ProjectWhereUniqueInput,
    @common.Body() body: ComponentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      components: {
        disconnect: body,
      },
    };
    await this.service.updateProject({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/projectEnvironments")
  @ApiNestedQuery(ProjectEnvironmentFindManyArgs)
  async findProjectEnvironments(
    @common.Req() request: Request,
    @common.Param() params: ProjectWhereUniqueInput
  ): Promise<ProjectEnvironment[]> {
    const query = plainToClass(ProjectEnvironmentFindManyArgs, request.query);
    const results = await this.service.findProjectEnvironments(params.id, {
      ...query,
      select: {
        createdAt: true,
        deletedAt: true,
        id: true,
        metadata: true,
        name: true,

        project: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/projectEnvironments")
  async connectProjectEnvironments(
    @common.Param() params: ProjectWhereUniqueInput,
    @common.Body() body: ProjectEnvironmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      projectEnvironments: {
        connect: body,
      },
    };
    await this.service.updateProject({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/projectEnvironments")
  async updateProjectEnvironments(
    @common.Param() params: ProjectWhereUniqueInput,
    @common.Body() body: ProjectEnvironmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      projectEnvironments: {
        set: body,
      },
    };
    await this.service.updateProject({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/projectEnvironments")
  async disconnectProjectEnvironments(
    @common.Param() params: ProjectWhereUniqueInput,
    @common.Body() body: ProjectEnvironmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      projectEnvironments: {
        disconnect: body,
      },
    };
    await this.service.updateProject({
      where: params,
      data,
      select: { id: true },
    });
  }
}
