/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AccountWhereUniqueInput } from "../../account/base/AccountWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { ComponentCreateNestedManyWithoutProjectsInput } from "./ComponentCreateNestedManyWithoutProjectsInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { ProjectEnvironmentCreateNestedManyWithoutProjectsInput } from "./ProjectEnvironmentCreateNestedManyWithoutProjectsInput";

@InputType()
class ProjectCreateInput {
  @ApiProperty({
    required: true,
    type: () => AccountWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AccountWhereUniqueInput)
  @Field(() => AccountWhereUniqueInput)
  account!: AccountWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => ComponentCreateNestedManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => ComponentCreateNestedManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => ComponentCreateNestedManyWithoutProjectsInput, {
    nullable: true,
  })
  components?: ComponentCreateNestedManyWithoutProjectsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  createdAt?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  deletedAt?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  metadata?: InputJsonValue;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: () => ProjectEnvironmentCreateNestedManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => ProjectEnvironmentCreateNestedManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => ProjectEnvironmentCreateNestedManyWithoutProjectsInput, {
    nullable: true,
  })
  projectEnvironments?: ProjectEnvironmentCreateNestedManyWithoutProjectsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  updatedAt?: Date | null;
}

export { ProjectCreateInput as ProjectCreateInput };
